### ISSUE TITLE
Service 'frontend' fails to build

### ISSUE THREAD

**Issue by jpieres** [limiaspasdaniel/YearlyBenefitsCalculatorWebSockets#2]
When executing:

`> docker-compose up --build`

Backend service builds ok.
Frontend service fails with the following error:

`Step 4/12 : COPY package*.json yarn.lock ./
ERROR: Service 'frontend' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder650929562/yarn.lock: no such file or directory`

Dockerfile for the frontend tries to do:

`COPY package*.json yarn.lock ./`

but there is no yarn.lock in the frontend

**Comment by 2snEM6** [comment]
Fixed [here](https://github.com/limiaspasdaniel/BenefitsCalculator/tree/0df65a08170f8c002d856ab8e7292098287d769e)
